Y = 'Y'
N = 'N'
CSV_FILE_EXTENSION = ".csv"
BINARY_PRED = "binary_pred"
ORIG_PRED = "orig_pred"
ORIG_PRED_TEMP = "orig_pred_temp"
ORIG_PRED_LOW = "orig_pred_low"
ORIG_PRED_HIGH = "orig_pred_high"
HL_ORIG_PRED = "hl_orig_pred"
OOS = "OOS"
STEP_1 = "step_1"
STEP_2 = "step_2"
STEP_3 = "step_3"
STEP_4 = "step_4"
FINAL_PREDICTION = "final_prediction"
SKU = 'SKU'
LOCATION = 'LOCATION'
DATE = 'DATE'
TARGET_CLASSIFICATION_BINARY_HL = "BINARY_HL_TARGET_CLASSIFICATION"
TARGET_REGRESSION = "TARGET_REGRESSION"
TARGET_REGRESSION_H = "H_REV_TARGET_RATIO"
REV_IP_QTY_EOP_SOH = "REV_IP_QTY_EOP_SOH"
TP_COUNT = 'TP Count'
FN_COUNT = 'FN Count'
TN_COUNT = 'TN Count'
FP_COUNT = 'FP Count'
TP_PERCENT = 'TP Percent'
FN_PERCENT = 'FN Percent'
TN_PERCENT = 'TN Percent'
FP_PERCENT = 'FP Percent'
PRECISION_PERCENT = 'Precision Percent'
RECALL_PERCENT = 'Recall Percent'
F1_SCORE = 'F1 Score'
ACCURACY = 'Accuracy'
