#!groovy

pipeline {
    agent any
     options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }
    stages {
        stage('build') {
            steps {
                echo 'build switch'
            }
        }
        stage("test"){
              steps{
                echo "pipenv run pytest"
              }
        }
        stage("publish_switch"){
              steps{
                sh "ls"
                sh "sh component/switch/pipeline/build.sh"
              }
        }
    }
}