ARG PYTHON_VERSION="3.8.15"
FROM python:${PYTHON_VERSION}

# Install jq
RUN apt-get update && \
    apt-get install -y jq && \
    apt-get clean

# Install pip.
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    pip3 install setuptools && \
    rm get-pip.py
RUN python3 -m pip install --upgrade pip

# Copy the JSON config file from the workspace into the image
COPY build.json /app/

# Install packages using versions from the config file
WORKDIR /app

# Calling the packages and their versions from JSON config
RUN python3 -m pip install -U $(cat build.json | jq -r '.package_versions | to_entries[] | "\(.key)==\(.value)"')

# Remove the JSON config file
RUN rm -f build.json

RUN rm -rf inference

RUN mkdir -p inference
COPY * inference/
WORKDIR inference

ENTRYPOINT ["bash", "build_test_production_model.sh"]